name: backstagetest-python-app-8-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sylweltan/backstagetest-python-app-8:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3

      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/backstagetest-python-app-8/values-dev.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-kind2.wiz.moultech.com/download/argocd-linux-amd64
          chmod +x argocd
          #sudo mv ./argocd /usr/local/bin/argocd
          mkdir -p ${HOME}/bin
          export PATH="${HOME}/bin:${PATH}"
          mv ./argocd ${HOME}/bin/argocd

      - name: argocd login
        shell: bash
        run: |
          ${HOME}/bin/argocd login argocd-kind2.wiz.moultech.com \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}

      - name: Ensure argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/CodeArchipelago/backstagetest-python-app-8.git"
          ${HOME}/bin/argocd repo list | grep -q $repo || ${HOME}/bin/argocd repo add $repo

          # Creates the argocd app
          ${HOME}/bin/argocd app get backstagetest-python-app-8 || ${HOME}/bin/argocd app create backstagetest-python-app-8 \
            --repo $repo \
            --path charts/backstagetest-python-app-8 \
            --dest-namespace dev \
            --dest-server https://kubernetes.default.svc \
            --values values-dev.yaml \
            --revision master \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Argocd app sync
        shell: bash
        run: |
          ${HOME}/bin/argocd app sync backstagetest-python-app-8
          ${HOME}/bin/argocd app wait backstagetest-python-app-8 --timeout 180
